name: Sonatype

on:
  push:
    branches:
      - main-fork

jobs:
  build:
    if: github.repository_owner == 'revelc' && ! contains(toJSON(github.event.head_commit.message), '[maven-release-plugin]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
          cache: 'maven'
      - name: Download Maven Wrapper
        run: mvn wrapper:wrapper "-Dmaven=3.9.7"
      - name: Deploy to Sonatype
        run: ./mvnw deploy -DskipTests -B --settings ./.mvn/settings.xml
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
